### ISSUE TITLE
Linux KVM and QEMU patch

### ISSUE THREAD

**Issue by wenhuizhang** [columbia/VIA#1]
Hi, @lixupeng 
Sorry for bothering, congrats on the paper. 
I was wondering if there are some available docs on KVM and QEMU patches for ARM CCA adaption please?
We are (Tiktok Sec, STE and IAAS team) are working on ARM CCA.
Is it possible to invite you over for a talk in details please?

wenhui.zhang@bytedance.com

**Comment by XuhengLi** [comment]
Hi @wenhuizhang,

Thank you for being interested in our work.

However, we are not aware of any publicly available documents for CCA KVM at the moment nor we are able to talk about the detailed implementation.

Best,

Xuheng

**Comment by wenhuizhang** [comment]
Hi, Xu Peng:

Thanks all the same!

Wenhui

**Comment by XuhengLi** [comment]
Just to be clear we have two authors Xupeng and Xuheng ;)

> Hi, Xu Peng:
> 
> Thanks all the same!
> 
> Wenhui

**Comment by wenhuizhang** [comment]
Thanks for the correction Xuheng ;)
